<?php

if( function_exists('acf_add_local_field_group') ):

$page_accueil = get_page_by_title('Accueil');

acf_add_local_field_group(array (
	'key' => 'informations-complementaires',
	'title' => 'Informations complémentaires',
	'fields' => array (
		array (
			'key' => 'field_55b8fa78a9847',
			'label' => 'Documents utiles',
			'name' => 'citeo_extra_documents',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Ajouter un document',
			'sub_fields' => array (
				array (
					'key' => 'field_55b8fabca9848',
					'label' => 'Document',
					'name' => 'citeo_extra_documents_item',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array (
			'key' => 'field_55b8fb5638201',
			'label' => 'Liens utiles',
			'name' => 'citeo_extra_links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Ajouter un lien',
			'sub_fields' => array (
				array (
					'key' => 'field_55b8fb6238202',
					'label' => 'Lien',
					'name' => 'citeo_extra_links_item',
					'type' => 'url',
					'instructions' => 'exemple : http://www.service-public.fr',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array (
					'key' => 'field_55b8fb6a38203',
					'label' => 'Libéllé du lien',
					'name' => 'citeo_extra_links_item_title',
					'type' => 'text',
					'instructions' => 'exemple : Service-public.fr',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_55b8fbbe66fbb',
			'label' => 'Ressources utiles',
			'name' => 'citeo_extra_ressources',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Ajouter une ressource',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '55b8fc8e65c81',
					'name' => 'citeo_extra_ressources_file',
					'label' => 'Document',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_55b8fbd766fbc',
							'label' => 'Document',
							'name' => 'citeo_extra_ressources_file_item',
							'type' => 'file',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '55b8fbe566fbd',
					'name' => 'citeo_extra_ressources_link',
					'label' => 'Lien',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_55b8fbee66fbf',
							'label' => 'Lien',
							'name' => 'citeo_extra_ressources_link_item',
							'type' => 'url',
							'instructions' => 'exemple : http://www.service-public.fr',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_55b8fbf466fc0',
							'label' => 'Libellé du lien',
							'name' => 'citeo_extra_ressources_link_title',
							'type' => 'text',
							'instructions' => 'exemple : Service-public.fr',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
		array (
			'key' => 'field_55b9e325e80fa',
			'label' => 'Contacts',
			'name' => 'citeo_extra_contacts',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Ajouter un contact',
			'sub_fields' => array (
				array (
					'key' => 'field_55b9e33ae80fb',
					'label' => 'Coordonnées du contact',
					'name' => 'citeo_extra_contacts_item',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'visual',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page',
				'operator' => '!=',
				'value' => (string) $page_accueil->ID,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'actualite',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'evenement',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;