<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'offres-demplois',
	'title' => 'Offres d\'emplois',
	'fields' => array (
		array (
			'key' => 'field_55b0efda47f40',
			'label' => 'Date limite de l\'offre',
			'name' => 'citeo_limit_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array (
			'key' => 'field_55b0f02247f41',
			'label' => 'Ressources',
			'name' => 'citeo_ressources',
			'type' => 'flexible_content',
			'instructions' => 'Ajouter une ou des ressources à l\'offres d\'emploi',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Ajouter une ressource',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '55b0f032649d3',
					'name' => 'citeo_ressource_file',
					'label' => 'Fichier',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_55b0f04e47f42',
							'label' => 'Fichier',
							'name' => 'citeo_ressource_file_item',
							'type' => 'file',
							'instructions' => 'Fichier de 20Mo maximum',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => 20,
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '55b0f07da98f5',
					'name' => 'citeo_ressource_link',
					'label' => 'Lien',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_55b0f088a98f6',
							'label' => 'Lien',
							'name' => 'citeo_ressource_link_item',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_55b0f099a98f7',
							'label' => 'Titre du lien',
							'name' => 'citeo_ressource_link_item_title',
							'type' => 'text',
							'instructions' => 'exemple : "Site de Pôle emploi"',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
		array (
			'key' => 'field_55b0f116c235e',
			'label' => 'Contacts',
			'name' => 'citeo_contacts',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Ajouter un contact',
			'sub_fields' => array (
				array (
					'key' => 'field_55b0f12ec235f',
					'label' => 'Coordonnées du contact',
					'name' => 'citeo_contacts_item',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'visual',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'emploi',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;
